# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
    - job: 
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo apt-get update
            sudo apt install git -y

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo git clone https://github.com/spring-projects/spring-petclinic.git
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'echo ''Hello world'''
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo apt-get update
            sudo apt install openjdk-21-jre-headless -y

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo apt-get update
            sudo apt install maven -y

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo mvn package




- stage: ReleasetoDev
  jobs:
    - job: 
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'echo ''Hello world'''
      
- stage: releaseToTest
  jobs:
    - job: 
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'echo ''Hello world'''
      
- stage: ReleasetoProd
  jobs:
    - job: 
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'echo ''Hello world'''
      